version: '2'
services: 
  rethinkdb:
    image: rethinkdb
    ports:
      - 8080:8080
      - 28015:28015
  redis:
    image: redis:3.0.7
    ports:
      - 6379:6379
  elasticsearch:
    image: elasticsearch:5.3
    ports:
      - 9200:9200
